### ISSUE TITLE
Connection won't work

### ISSUE THREAD

**Issue by TryDev07** [marvin-mangold/-S7-PLC_MySql_MariaDB#1]
Hello, I don't understand how but i keep getting the follow error code W#16#0002 i know this means that the TCP connection is not established but i cannot figure out why. I tried local databases public databases etc. I even checked if my connection was working using another language java in there it works just fine but once i use the same values in the function it just doesn't connect.

**Comment by marvin-mangold** [comment]
Hello, do you toggle the „connect“ Input or do you set to True once.

**Comment by marvin-mangold** [comment]
Maybe you are using an already used „Connectiont_id“ or the wrong „hardware_id."

**Comment by TryDev07** [comment]
How do i know if i have the right id's for botg?

**Comment by marvin-mangold** [comment]
For “Connection_ID”:
If there are no other TCP communication in your PLC / TIA Project you can use “1”.
If there are other TCP connections using TCP like the FB TCON then you should choose a number that is not used.

For “Hardware_ID”:
You need to choose the PLC port where the Ethernet cable to your SQL Server is plugged in.
Take a look at the image below:
![HardwareID](https://user-images.githubusercontent.com/10088323/224356251-2145b98d-c65e-42e1-9571-d35ed7a06115.png)

**Comment by TryDev07** [comment]
> For “Connection_ID”: If there are no other TCP communication in your PLC / TIA Project you can use “1”. If there are other TCP connections using TCP like the FB TCON then you should choose a number that is not used. For “Hardware_ID”: You need to choose the PLC port where the Ethernet cable to your SQL Server is plugged in. Take a look at the image below: ![HardwareID](https://user-images.githubusercontent.com/10088323/224356251-2145b98d-c65e-42e1-9571-d35ed7a06115.png)

I have set the connection_id to 1 aswell because i i'm only using one tcp connection. and the hardware_id i left it on the same setting as in your example project.

Take a look at my function block.
![image](https://user-images.githubusercontent.com/58628969/224428049-07f2bb47-8071-4ccd-890c-b1cff13e902c.png)

**Comment by marvin-mangold** [comment]
What plc model are you using? And in which Ethernet Port is the cable plugged in? X1 or X2

**Comment by marvin-mangold** [comment]
Take a look in your DB2 and Check the Variable State.Tcon.Status

**Comment by TryDev07** [comment]
Well actually i'm using plcsim and i've added the 1200 cpu there

**Comment by marvin-mangold** [comment]
Do you have plcsim Professional? Because in the Standard Version of plcsim you can not simulate network communication. 

#edit: Plcsim Advanced

**Comment by TryDev07** [comment]
> Do you have plcsim Professional? Because in the Standard Version of plcsim you can not simulate network communication.

you mean the advanced variant or?

**Comment by TryDev07** [comment]
> What plc model are you using? And in which Ethernet Port is the cable plugged in? X1 or X2

![image](https://user-images.githubusercontent.com/58628969/224432545-44e25da7-8b34-428d-abf0-5131ae813579.png)
this it what is says in the simulator

**Comment by TryDev07** [comment]
> Take a look in your DB2 and Check the Variable State.Tcon.Status

its switching between busy and error whith status codes:
16#7002
16#80C5
16#7001

**Comment by marvin-mangold** [comment]
16#80C5 says the Communication Partner refuses the connection. So your sql Server is blocking the communication. Maybe you need to make changes in the server settings

**Comment by TryDev07** [comment]
> 16#80C5 says the Communication Partner refuses the connection. So your sql Server is blocking the communication. Maybe you need to make changes in the server settings

well thats weird because i'm just running a local mysql database using XAMPP. So there is no firewall blocking anything like you would expect it to be on an external server.

**Comment by marvin-mangold** [comment]
I think there must be a setting to allow tcp connections for user "root" in the sql Server. 

Or try to create a new user in your database and connect with this instead of root like mentioned in my description:

You should create a new user for connecting to plc by typing following into your server commandline:
1.    CREATE USER 'your_new_username'@'%';
2.    ALTER USER 'your_new_username'@'%' IDENTIFIED WITH 'mysql_native_password';
3.    ALTER USER 'your_new_username'@'%' IDENTIFIED BY 'your_new_password';
4.    GRANT ALL PRIVILEGES ON your_databasename.your_tablename TO 'your_new_username'@'%';
5.    FLUSH PRIVILEGES;

**Comment by marvin-mangold** [comment]
![image](https://user-images.githubusercontent.com/10088323/224484025-401a0d1b-560b-4fe7-97c3-9b7082416ef2.jpeg)

**Comment by TryDev07** [comment]
> I think there must be a setting to allow tcp connections for user "root" in the sql Server.
> 
> Or try to create a new user in your database and connect with this instead of root like mentioned in my description:
> 
> You should create a new user for connecting to plc by typing following into your server commandline:
> 
>     1. CREATE USER 'your_new_username'@'%';
> 
>     2. ALTER USER 'your_new_username'@'%' IDENTIFIED WITH 'mysql_native_password';
> 
>     3. ALTER USER 'your_new_username'@'%' IDENTIFIED BY 'your_new_password';
> 
>     4. GRANT ALL PRIVILEGES ON your_databasename.your_tablename TO 'your_new_username'@'%';
> 
>     5. FLUSH PRIVILEGES;

i will try to setup a ubuntu vm with sql on it and try to create a user in that way

**Comment by TryDev07** [comment]
i've tried it and i still get the same code 16#80C5

![image](https://user-images.githubusercontent.com/58628969/224492290-2f92df33-0829-4268-b0e3-0ed391a5f543.png)
![image](https://user-images.githubusercontent.com/58628969/224492319-7794c19e-5b7d-4991-8b6e-b87cfa425ef4.png)
^^ here its not working in the plc using the simulator.

In java it works just fine with the same configuration of password username and database
![image](https://user-images.githubusercontent.com/58628969/224492383-e0a9bebb-b299-4227-b9e9-20ec1cb760e1.png)

**Comment by marvin-mangold** [comment]
At the moment the siemens support site is down. But there are some google results searching for "80C5 plcsim" i will have a look later.

With a real plc everything works, maybe a plcsim issue.

**Comment by TryDev07** [comment]
> At the moment the siemens support site is down. But there are some google results searching for "80C5 plcsim" i will have a look later.
> 
> With a real plc everything works, maybe a plcsim issue.

i'll try to get a real plc tommorrow from work and check it out if thats the issue.

**Comment by TryDev07** [comment]
> > At the moment the siemens support site is down. But there are some google results searching for "80C5 plcsim" i will have a look later.
> > With a real plc everything works, maybe a plcsim issue.
> 
> i'll try to get a real plc tommorrow from work and check it out if thats the issue.

i've checked it out with an actual plc and it seems to work properly in there. thanks for the support.
