### ISSUE TITLE
S7-1200 <->MySQL: Send and receive buffer

### ISSUE THREAD

**Issue by krzysztof-zaber** [marvin-mangold/-S7-PLC_MySql_MariaDB#3]
Dear Mr Marvin,

In the beginning I have to say that you've made a really nice MySQL connection library for s7-1200 PLCs. I am testing it with 1212C and I can report it works just fine. I can do almost everything you described in the library. Connections, sending requests, receiving information from MySQL database, pinging... everything just works. I am currently checking boundaries what those smallest PLC-s can do and I visited your project. Great work. 

I have 3 questions about this library (I do not have much experience with MySQL databases, so it might be only my ignorance):

1. I tried to use a buffer for sending requests. I made a table in MySQL database which have "too much columns". Because of that the string request/query would take more than 254 bytes. To solve the problem I am firstly sending INSERT query with request to make a row and fill it with default values of the coulmns, and then I am sending several UPDATE queries which "part-by-part" are updating this row. This works just fine...but I would like to send them together to some buffer, from which they would be sent when the previous query will be finished. I started to making such buffer, but I checked in the code, that it looks like you made something like that... but I do not know, or do not understand how to use it. Is this buffer for sent and received queries available at this stage of the project? If so, can you write an example how to use it? For a test I would like to disconnect plc from the internet, and fill the buffer with the data once per minute. After that I would like to connect internet back, and check if all those queries will be sent to the database. Is it possible with your buffer in this library? If so, how to do it?

2. After every query error (mostly SQL error 0012) I am getting disconnected from the SQL server. Is this normal? Because of that when i want to send another query (which might not cause error) I have to switch "connect" bit back to 0 and then again to 1. Is this disconnect needed? Can't this FB just wait for another query (which might be proper) without disconnecting from the MySQL server?

3. I tried to make some changes to your library, to change queries from Strings to WStrings (because of this 254 byte string limit). At some point I couldn't guess if errors I received were from my code or there was something directly connected with MySQL communication, and I gave up. I was reading many topics in Siemens forum about SQL queries, and almost no one is using WStrings for sending queries, while Strings are sometimes simply too small. Is there a reason for that, which also limited you in this library to only use 254-byte Strings instead WStrings?

Sorry for long essay. 

With regards
Krzysztof Ząber

**Comment by marvin-mangold** [comment]
Hello,

thanks for the positive review.

1. you can combine all 6 Strings (6 * 254 Bytes) to one big SQL command:

[image: grafik.png]


2. The connection gets disconnectd because of some error. normally you keep
connected and do not need to disconnect and reconnect again.
If the Error " SQL error 0012" comes from my Functionblock, then you can
check the errormessage wich comes from the SQL server by looking into the
Instance Datablock of the Functionblock.
instancedatablock -> errorPacket -> ERROR_MESSAGE

if there are new or other questions, just ask. i can help to understand the
errormessage you will find in the erromessage from server



Am Mo., 11. März 2024 um 11:55 Uhr schrieb krzysztof-zaber <
***@***.***>:

**Comment by marvin-mangold** [comment]
Hello,

thanks for the positive review!

1. you can combine all 6 Strings (6 * 254 Bytes) to one big SQL command:


![unnamed](https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/assets/10088323/af25744f-3c75-4ea0-9fd7-548126adb693)


2. The connection gets disconnectd because of some error. Normally you keep
connected and do not need to reconnect.

If the " SQL error 0012" comes from my functionblock, then you can
check the errormessage wich comes from the SQL server by looking into the
Iinstance datablock of the functionblock.
instancedatablock -> errorPacket -> ERROR_MESSAGE

If you have the errormessage i can check / give further informations what causes the error.

**Comment by krzysztof-zaber** [comment]
Hello again,

Thank you for express answer.

I just found the reason why I was receiving 0012 error. In my database I set RTC_Clock column as unique, so when i tried insert again rows with different types of commands, I was always reciving this error, which was always disconnecting my connection to database. 

When i found my mistake with unique value, now I can see that I can send more than 254 byte strings. This really makes it easier, and simply works. Again, great work.

However the main question still stays: 

How to use buffer in your library? When I would like to send a query, for example once per minute, and PLC will loose internet connection for some time. How can I use buffer in your library to buffer queries from the last 60 minutes or 24 hours? Is buffering happening automatically when query will take too long and when in query table another query will show up? Or maybe I have to somehow enable it? Is this buffer in the library even a buffer in the way I am describing it?
Thank you.

**Comment by marvin-mangold** [comment]
A buffer like you imagine is not implemented. 

If I were you, I would create a LIFO Functionblock that buffers the queries and processes them one after the other. 
If processing is successful, the first entry gets deleted and all following entries are moved up one,
if processing is not successful, the first entry stays in the LIFO and new entries are placed at the end.

There is a good LIFO FB from Siemens. Take a look at: 
https://support.industry.siemens.com/cs/document/109479728/library-of-general-functions-(lgf)-for-simatic-step-7-(tia-portal)-and-simatic-s7-1200-s7-1500?dti=0&dl=en&lc=de-DE
If you contact Siemens support you can get this library for older TIA Versions.

------------------------------------------------------------------------------------------------------------------------------------------
The buffersize in my functionblock refers to the amount of bytes sent and received via TCP.
For example:
If you want to execute a SQL Query that has a lot of data as an answer, you can adjust the constants "Buffersize", "Rows" and "Columns". 
Because a query command like "SELECT * FROM table;" would return more data than the block can process in the standard implementation.

**Comment by marvin-mangold** [comment]
Maybe you can increase the "Buffersize" constant in the functionblock and take a "Array 0..20 of String" or bigger as query command data to make really big SQL commands. 

The functionblock writes all of the query-strings into the sendbuffer and sends one command Package to the SQL-Server.
As Long as the data fits in the "Buffersize" this should work.

**Comment by krzysztof-zaber** [comment]
Dear Mr Marvin,

I will try to make my own buffer for those queries. I am familiar with LGF libraries. The main problem with this buffer will be with buffering queries of different length. If I will have this big INSERT query, which is over 254 bytes, then I will have to use the method you wrote before, and cut out several queries, which you will glue together later. With short queries only one query table row will be enough. It means this buffer will have to sometimes buffer several rows to save one query, and sometimes only one row. Buffer with Array of Arrays? This might be a little bit tricky.

The best option to solve this problem would be if I could write query of over 254 bytes length in just one queryData row. In such case, making a buffer for one row queries would be a lot easier (for example executing LIFO table which you mentioned). I will try to figure it out, one way or another.

Thank you for your enormous help!

**Comment by marvin-mangold** [comment]
To use a WString instead of an Array of Strings you need to write a new function wich works like my function „WRITE_FIXED_LENGTH_STRING“.

Because of the size of a WString the Buffersize needs to be greater than 32000 Bytes, because a WString can contain 16382 letters with 2 Bytes for each letter. 

I am Not sure if the SQL Server can work with this 2 Byte WChars. As far as i know the Chars are encoded with utf8 (8-Bit UCS Transformation Format) 1 Byte per letter.
So you need convert each Wchar to Char if the Char is convertable.

If this works then it need to replace this Part of my Code:


----------------------------
// write sql statement from array
// get array bounds
	                #querystatement.low := LOWER_BOUND(ARR := #querydata, DIM := 1);
	                #querystatement.up := UPPER_BOUND(ARR := #querydata, DIM := 1);

FOR #querystatement.counter := #querystatement.low TO #querystatement.up DO
	                    #temp."string" := #querydata[#querystatement.counter];
	                    "WRITE_FIXED_LENGTH_STRING"(error => #retval."bool", data := #sendBuffer, start := #counter, bytes := LEN(#temp."string"), str := #temp."string");

END_FOR;

----------------------------

**Comment by krzysztof-zaber** [comment]
I tried another approach. Since your library already covered glueing strings before sending to the MySQL server, I made not one but several LIFO tables with one internal DB as buffer for those Strings. I am gathering all variables in several FBs in which I am glueing them together in those shorter Strings. Because of that, it comes natural to buffer them here before sending them to your queryData table. Everything works just fine. But there is always a BUT :(

If I want a direct access to the buffer registers, then I have to turn off "Optimized block access". In such situation, I am limited to 65543 bytes for addressable memory.

![image](https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/assets/162978518/45b08010-0417-459e-a074-ccd1fa44e842)

If I allow "Optimized block access", then I can work with more than 65543 bytes, but another problems (more obvious) occurs. Size of "Work memory". If my final String weights 350 bytes, then in case of internet absence, buffering String once per minute will lead to over 20kB of memory needed to store just 1 hour of data. It is often not too much (you can have internet problems at remote station for several hours or even days). If, for example, we buffer 5 hours of strings, we will need a little bit over 100kB of memory, while 100kBs is all we have in work memory area in 1212C PLC.

![image](https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/assets/162978518/b777e367-8c07-4ec9-8751-0daaaf0453e7)

![image](https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/assets/162978518/55388079-2c5b-4cd5-87ea-af21cac5c206)

I tried even using "Load" memory to work as a buffer (if I will access it once a minute and if needed just read and clear it, then it should be possible)... and according to complier it is. The problem here is that LGF LIFO FB library does not want to work with buffer table located in "Load memory" (option "Only store in load memory"). 

I think I reached the limit for such Strings buffer, and it doesn't matter if it is stored as several smaller strings or as one bigger string. Those strings together take so much memory, that we simply reach the maximum of memory which we can use in our PLC. This problem is not with your library (which is great), but with the small amount of memory which we receive from siemens in those smallest PLCs.

Maybe there is some workaround to use Load memory in PLC or on SD Card instead of Work memory, which is always very limited across all S7-1200 PLCs.

**Comment by marvin-mangold** [comment]
Maybe you can try to save just the Variables and not the SQL command Strings.
Then create the String only for one entry in your Buffer.
All the Letters in the SQL command need so much data and the Variables just some Bytes.

**Comment by krzysztof-zaber** [comment]
I think that, by going this way in my case I will save 20-30% of memory space (mostly because of lack of commas). With the table I am working on, I squeezed everything i could into the final query which your library is sending. It looks like this (57 items - 337 bytes):

> `INSERT INTO data_table VALUES (DEFAULT,120,DEFAULT,"2024-03-06 14:26:15",17,321,0,0,5.5,12.3,17.1,30.1,124.2,143.4,6.2,13.8,16.1,4.1,10.2,46.3,330.1,346.1,358.1,320.1,330.2,331.5,15.9,44.1,44.3,44.2,24.7,231.1,230.9,230.2,430.1,429.2,429.8,23.1,23.2,23.0,17.1,16.9,17.2,50.1,39.1,37.4,38.9,2768.1,46.1,49.1,41.7,374,321,222,333,444,555);`

The problem with compressing it even more is that, most of those variables are in REAL values, and they also take a lot of memory. I could also make some additional operations like multiplying every value by 10, convert to INT/WORD and then store them in buffer. When there will be a time to send them to a query, i could again divide them by 10 to make this enormous one query. 

Another problem here is a time of operations. When I will have to do some math calculations before sending several variables to the buffer and after that getting them back... ok. Nothing dramatic. But when i have 30 or 50 of them, milliseconds start to add to each other. Depending what else will there be in the program, it might be a problem or not.... not mentioning troubleshooting in case of error. 

I plan to move from 1212c to 1215C, so I will have double amount of Work memory. It will allow me to get some more hours of buffered data, but it would be great if there was a way to access Load memory to use it for buffer purposes. In such case we would be talking about days or even weeks of buffered data, because S7-1200 PLCs have 2 or 3 or 4 MB of this type of memory.

I am still searching for the best solution. It is very painful how much work memory we are getting from Siemens in such nice PLCs.

**Comment by marvin-mangold** [comment]
You could try to read/write the data from/to a Memory Card.

**Comment by krzysztof-zaber** [comment]
> You could try to read/write the data from/to a Memory Card.

That is probably the last option in this situation, however I do not know if Siemens has some implemented code for register shifting to prevent damaging of sd card memory sectors. In other words, SD card has limited number of reads and writes and it would be nice to know if PLC will not kill it too fast. I will check that direction.

One last question: 
When I will want to send a data from the buffer to the query, I need to know when the data was sent, so I will be able to 'pop' old query from the LIFO table and send another one to the server. Do I need to directly take that information from the static variable inside your FB (#state.sent) or there is some other indicator I can use for this purpose? How will I know that the query was sent? Maybe I should shift state.sent switch to the output section to see this information outside of the library?

At this moment the only indicator I can use to indicate if the query was done is when I switch the query bit from 0->1, and it goes back to 0 without giving other status than 16#0000.

**Comment by marvin-mangold** [comment]
Maybe you should consider adapting the concept so that the SQL server is always accessible. (mini PC with SQL server right next to the PLC) and collect/send the data elsewhere.

After the PLC sends the SQL command to the server, the server responds with OK or ERROR. As soon as the OK response arrives, the query bit is reset and state keeps 16#0000.
If anything was bad there will be a state > 16#0000.

If the query bit gets false and state == W#16#0000 the data is successful sent to Server. Then you can fill the Strings and set the query bit to sent the next data.

**Comment by krzysztof-zaber** [comment]
Thank you for explanation. It means I assumed correctly how it query confirmation works.

I have one more question about the need of buffering (your patience is incredible :)). If, after the error, your library disconnects from the SQL server, then I have to detect this situation and reset this connection. If I will not do it, other queries will start going to their buffers, while they shouldn't have to. How can I disable disconnecting from SQL server after getting the error? If I will be sending several queries to several tables in database, then if one query will recive error (for example, doubled UNIQUE value with one row), then after sending this query I will not have to reset connection with the database. Is it some kind of rule, or a good habit to disconnect from the SQL server after receiving error message? 

I think it is good for debigging at the designing stage, but with normal work, when somehow one regular query out of 5 different queries has an error, then it is good to not lost option to send other queries without delay. Am I missing something here? Can i disable this "necessity" of disconnection?

**Comment by marvin-mangold** [comment]
Open my functionblock and search for the line:

```

#state.status := W#16#0012;

```

![image](https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/assets/10088323/90323376-ce15-4ffb-8b8a-dc4d76428b9a)

This is where the sequenzer will set the error state if the SQL-Server responds with an ERROR-Packet to one of the PLCs commands. 

If you change the line to:

```

IF #query THEN
    #state.status := W#16#0003;
    #state.step := 100;
ELSE
    state.status := W#16#0012;
END_IF;

```

Then any Error from a query will not lead to an disconnect. But you get state 16#0003 in this case. And you can send the next query.

Every state >= 16#0010 leads to a disconnect.

![image](https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/assets/10088323/80d69eb0-367a-4324-b87a-404db9b94649)

**Comment by krzysztof-zaber** [comment]
I did this change and everything works just like you described. Now even if some query will get an error, other queries will be able to be sent/received without the need of reconnecting to the MySQL server. What is more, this error number (0003) tells that some query had error since last connection, and I can check it in error_message register (after reconnecting error message goes to 0000, which works as expected). There is only one problem here: When previous error was 0003, after sending next, but proper query, error state doesn't change to 0000, but still stays 0003. It means it is harder to indicate properly if query was sent or not. I will figure it out.

I also found out that, when PLC will lost connection to the internet I do not have to disconnect and reconnect connection to SQL server. Your library will show error 0002 (TCP connection is not established), will wait until internet "comes back" and reconnects itself to the SQL server. I do not know if this is one of the features of tcon functions themselves, but it works great. There is no need to monitor this connection all the time, but just from time-to-time check or reset it. 

I think I've learned most of the features you implemented here. It would be great if the query array would clear itself after sending every query, but I can also do it by myself, by filling those query rows with empty data ('').

If you will have some more ideas, which I could check/use, please let me know. If not, we can close this issue.

Thank you very much for your help and your time. Great library which will help a lot of people.

Cheers
Krzysztof Ząber

**Comment by marvin-mangold** [comment]
_**There is only one problem here: When previous error was 0003, after sending next, but proper query, error state doesn't change to 0000, but still stays 0003. It means it is harder to indicate properly if query was sent or not. I will figure it out.**_

Go to my code and search for the line: "#state.step := 100;".
After this line you can insert the line: "#state.status := W#16#0000;" to overwrite the 0003 error when the next query was ok.

_**It would be great if the query array would clear itself after sending every query**_

Yes thats right, but maybe someone does not want this to happen. So i decided to let the user do what they want with the strings.

**Comment by krzysztof-zaber** [comment]
> Go to my code and search for the line: "#state.step := 100;". After this line you can insert the line: "#state.status := W#16#0000;" to overwrite the 0003 error when the next query was ok.

Simply works :)


> _**It would be great if the query array would clear itself after sending every query**_
> 
> Yes thats right, but maybe someone does not want this to happen. So i decided to let the user do what they want with the strings.

Yeah. Understandable. I will just send empty strings to the query array to clear it before every query. It is not a problem.

Thank you for help.
