### ISSUE TITLE
How to make multiple connections from S7-1200 to the same mysql server?

### ISSUE THREAD

**Issue by liubing** [marvin-mangold/-S7-PLC_MySql_MariaDB#4]
Hi,

I have managed to use this library to connect to a MariaDB instance and to perform SQL queries successfully. But when I try to make two simultaneous connections to the same db server, it doesn't work.

I'm aware that it is only possible to make one TCP connection per ip/port (S7 PLC restriction), so the first thing I do is to create port proxy on the server machine with this command (Windows):
```
netsh interface portproxy add v4tov4 listenport=3307 listenaddress=192.168.0.86 connectport=3306 connectaddress=192.168.0.86 protocol=tcp
```
After that I can connect to port 3306 or 3307 without any problem as long as there is only one connection.
But if I make two connections simultaneously (one to 3306 and one to 3307), only one will succeed.

My questions are:
Is it possible to make multiple connections from S7-1200 to the same server with this library?
If there is indeed such a restriction, does it come from the PLC itself or from the library?

Thank you.

**Comment by marvin-mangold** [comment]
I assume that you have tested that both connections work individually and you now have a problem if both connections are to be active on the PLC at the same time.

I am not aware of such a limitation. The only thing I can think of at first is that different numbers must be selected at the input "connectionID" for each Funtionblock call. 

This means that the first Funktionblock is called with the "connection_ID" 1, the second with the "connectionID" 2.

The data sheet of the PLC states how many OUC (Open User Communication) connections can be active at the same time.

**Comment by liubing** [comment]
After more tests we find out that the second functionblock always fails.

If there is only 1 FB (3306) put into the program, everything works fine; but if you put a second FB (3307) into the program, it won't connect to the server, **even if the first FB is currently not active**. We use TCP packet capture tool to monitor the network, and we found that the TCP connection of the second FB did not establish at all (no SYN packet sent).

It has nothing to do with TCP resource contention, it seems that only the first FB can work, and somehow its mere presence blocks the functionality of more FBs.

**Comment by marvin-mangold** [comment]
Do you get an Error at the Status-Output of the failing FB?

**Comment by liubing** [comment]
Yes. After the 1st FB connects successfully, the 2nd FB reports `12 SQL error, for further information see instancedatablock.errorPacket.ERROR_MESSAGE` and `errorPacket.ERROR_MESSAGE` shows `Host $'192.168.0.10$' is blocked because of many connection errors; unblock with $'mysqladmin flush-hosts$'`. It looks like an error message from the server but actually it is not because the TCP connection from the 2nd FB to the server is never established.

Fortunately, the puzzle is finally solved by tweaking some PLC settings. There is a property in CPU page called 'load of the communication loop' (actually I don't know what that means), changing it from `20%` to `50%`, and the problem immediately goes away, both FBs work fine magically.

Thank you for your help, and thank you for contributing such a good open source library to break such a closed ecosystem of the PLC world.

**Comment by mkdthanga** [comment]
I tried to establish connections from 2 simulataneous instances of "MySql_MariaDB_Client" within same function block, one after another (but with 2 different instance DBs), but the 2nd instance failed to connect although their instance DBs & their connection IDs are different (see screenshot). 

PLC: S7-CPU 1516F-3 PN/DP
I changed CPU setting > Communication load from 20% to 50%, (as mentioned above) but still 2nd FB can't connect.

Question:
1.  Is it only one TCP connection per ip/port possible ? Should Proxy port must be created in database server machine (as shown above)?
2. #tcpInfo.LocalPort is 2000 for both instances, since it is hardcoded inside the client FB itself, does it cause this tcp problem?

<img width="1573" height="1004" alt="Image" src="https://github.com/user-attachments/assets/c312ae5d-397f-4744-9e47-d133749b045e" />

<img width="567" height="462" alt="Image" src="https://github.com/user-attachments/assets/00d44f3a-f2e7-45e0-aed5-97accd4b6b0a" />

Any help would very much appreciated :)

**Comment by marvin-mangold** [comment]
You can try if it works if you add the local port as input and set it differently for each instance. One with port 2000 and one with port 2001.

Possibly it is set in the sql server that the user with whom the sps logs in may only have one simultaneous connection.

What is the errortext shown in the idb at error packet?

**Comment by mkdthanga** [comment]
it worked fine with different local ports itself (without need for proxy ports):

<img width="1907" height="1046" alt="Image" src="https://github.com/user-attachments/assets/9944d5bd-810c-4093-aa30-bf3bab86d953" />

**Comment by marvin-mangold** [comment]
I've updated the project with an extra input for the local port.
