### ISSUE TITLE
Can connect but does not receive anything

### ISSUE THREAD

**Issue by TWPLE** [marvin-mangold/-S7-PLC_MySql_MariaDB#7]
I have added this PLC code to a S7-1511 and I am able to connect to the database.
But I am not able to get nay results from PING or any SELECT commands.
Adding a faulty SQL command is faulting the FB correctly

Is there limitations in data types I am trying to read ? .... It is Float, String and Integers

**Comment by marvin-mangold** [comment]
Do you know wireshark? This allows you to view and record the communication between plc and the database. I can take a look at that. I can't explain to myself at the moment why that could be.

**Comment by TWPLE** [comment]
I will take a look in wireshark .... it makes good sense. Just wanted to make sure it wasn't anything obvious (I didn't catch :D)
Thanks

**Comment by marvin-mangold** [comment]
Maybe there is a new database version or the connection ID of the PLC is already used by another function block.

Maybe the user for the PLC in the database is not set up correctly.
So the commands are not allowed.

Have you set up the user, password and authentification as described in the readme?

What value is at the FB Output "Status" After sending a command?

As long as the ping function does not work, there is a problem
